openapi: "3.0.0"
info:
  version: 1.0.0
  title: RMI PACTA
  description: |
    API for interacting with RMI's Paris Agreement Capital Transition Assessment (PACTA) infrastructure
  termsOfService: TODO
  contact:
    name: Silicon Ally
    email: contact@siliconally.org
    url: https://siliconally.org
  license:
    name: MIT
    url: https://mit-license.org/
servers:
  - url: TODO
definitions:
  Language:
    type: string
    enum: &LANGUAGES
      - en
      - fr
      - es
      - de
paths:
  /pacta-version/{id}:
    get:
      summary: Returns a version of the PACTA model by ID 
      operationId: findPactaVersionById
      parameters:
        - name: id
          in: path
          description: ID of pacta version to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: pacta response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PactaVersion'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      summary: Updates a PACTA version 
      description: Updates a PACTA version's settable properties 
      operationId: updatePactaVersion
      parameters:
        - name: id
          in: path
          description: ID of PACTA version to update
          required: true
          schema:
            type: string
      requestBody:
        description: PACTA Version object properties to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PactaVersionChanges'
      responses:
        '200':
          description: pacta version updated successfully 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptySuccess'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    delete:
      summary: Deletes a pacta version by ID
      description: deletes a single pacta version based on the ID supplied
      operationId: deletePactaVersion
      parameters:
        - name: id
          in: path
          description: ID of pacta version to delete
          required: true
          schema:
            type: string 
      responses:
        '200':
          description: pacta version deleted successfully 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptySuccess'  
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  /pacta-version/{id}/set-default:
    post:
      summary: Marks this version of the PACTA model as the default
      operationId: markPactaVersionAsDefault 
      parameters:
        - name: id
          in: path
          description: ID of pacta version to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: updated successfully 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptySuccess'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
  /pacta-versions:
    get:
      summary: Returns all versions of the PACTA model 
      operationId: listPactaVersions
      responses:
        '200':
          description: pacta versions 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PactaVersion'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Creates a PACTA version 
      description: Creates a PACTA version
      operationId: createPactaVersion
      requestBody:
        description: PACTA Version object properties to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PactaVersionCreate'
      responses:
        '200':
          description: pacta version created successfully 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptySuccess'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /initiative/{id}:
    get:
      summary: Returns an initiative by ID 
      operationId: findInitiativeById
      parameters:
        - name: id
          in: path
          description: ID of the initiative to fetch 
          required: true
          schema:
            type: string
      responses:
        '200':
          description: the initiative requested 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Initiative'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      summary: Updates an initiative
      description: Updates an initiative's settable properties 
      operationId: updateInitiative
      parameters:
        - name: id
          in: path
          description: ID of the initiative to update
          required: true
          schema:
            type: string
        - name: body
          in: query
          description: initiative object properties to update
          required: true
          schema:
            $ref: '#/components/schemas/InitiativeChanges'
      responses:
        '200':
          description: initiative updated successfully 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptySuccess'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    delete:
      summary: Deletes an initiative by id
      description: deletes an initiative based on the ID supplied
      operationId: deleteInitiative
      parameters:
        - name: id
          in: path
          description: ID of initiative to delete
          required: true
          schema:
            type: string 
      responses:
        '200':
          description: initiative deleted successfully 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptySuccess'  
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /initiatives:
    get:
      summary: Returns all initiatives 
      operationId: listInitiatives
      responses:
        '200':
          description: gets all initiatives 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Initiative'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Creates a initiative
      description: Creates a new initiative 
      operationId: createInitiative
      requestBody:
        description: Initiative object properties to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitiativeCreate'
      responses:
        '200':
          description: initiative created successfully 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptySuccess'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /user/{id}:
    get:
      summary: Returns a user by ID
      description: Returns a user based on a single ID
      operationId: findUserById
      parameters:
        - name: id
          in: path
          description: ID of user to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: user response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      summary: Updates user properties
      description: Updates a user's settable properties 
      operationId: updateUser
      parameters:
        - name: id
          in: path
          description: ID of user to update
          required: true
          schema:
            type: string
      requestBody:
        description: User object properties to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserChanges'
      responses:
        '200':
          description: the new user object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptySuccess'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    
    delete:
      summary: Deletes a user by ID
      description: deletes a single user based on the ID supplied
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          description: ID of user to delete
          required: true
          schema:
            type: string 
      responses:
        '200':
          description: user deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmptySuccess'  
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              
components:
  schemas:
    Language:
      type: string
      enum: *LANGUAGES

    PactaVersionCreate:
      type: object
      required:
        - name
        - description
        - digest
      properties:
        name:
          type: string
          description: the human meaningful name of the version of the PACTA model 
        description:
          type: string
          description: Additional information about the version of the PACTA model 
        digest:
          type: string 
          description: The hash (typically SHA256) that uniquely identifies this version of the PACTA model. 

    PactaVersion:
      type: object
      required:
        - id 
        - name
        - description
        - digest
        - createdAt 
        - isDefault
      properties:
        id:
          type: string
          description: Unique id of the pacta version - system assigned 
        name:
          type: string
          description: the human meaningful name of the version of the PACTA model 
        description:
          type: string
          description: Additional information about the version of the PACTA model 
        digest:
          type: string 
          description: The hash (typically SHA256) that uniquely identifies this version of the PACTA model. 
        createdAt:
          type: string 
          format: date-time
          description: The time at which this version of the PACTA model was created 
        isDefault:
          type: boolean 
          description: Whether this version of the PACTA model is the default version 

    PactaVersionChanges:
      type: object
      properties:
        name:
          type: string
          description: the human meaningful name of the version of the PACTA model 
        description:
          type: string
          description: Additional information about the version of the PACTA model 
        digest:
          type: string 
          description: The hash (typically SHA256) that uniquely identifies this version of the PACTA model. 

    InitiativeCreate:
      type: object
      required:
        - id
        - name
        - language
      properties:
        id:
          type: string
          description: the human readable identifier for the initiative, can only include alphanumeric characters, dashes and underscores
        name:
          type: string
          description: the human meaningful name of the version of the initiative
        affiliation:
          type: string
          description: the group that sponsors/created/owns this initiative 
        publicDescription:
          type: string
          description: Additional information about the initiative 
        internalDescription:
          type: string
          description: Additional information about the initiative, for participants only 
        requiresInvitationToJoin:
          type: boolean 
          description: If set, only users who have been invited to join this initiative can join it, otherwise, anyone can join it. Defaults to false.
        isAcceptingNewMembers:
          type: boolean 
          description: If set, new users can join the initiative. Defaults to false.
        isAcceptingNewPortfolios:
          type: boolean 
          description: If set, users that are members of this initiative can add portfolios to it.
        language:
          description: The language this initiative should be conducted in. 
          type: string
          enum: *LANGUAGES
        pactaVersion:
          type: string
          description: The id of the PACTA model that this initiative should use, if not specified, the default PACTA model will be used. 

    Initiative:
      type: object
      required:
        - id
        - name
        - affiliation
        - publicDescription
        - internalDescription
        - requiresInvitationToJoin
        - isAcceptingNewMembers
        - isAcceptingNewPortfolios
        - pactaVersionId
        - language
        - createdAt 
      properties:
        id:
          type: string
          description: the human readable identifier for the initiative, can only include alphanumeric characters, dashes and underscores
        name:
          type: string
          description: the human meaningful name of the version of the initiative
        affiliation:
          type: string
          description: the group that sponsors/created/owns this initiative 
        publicDescription:
          type: string
          description: Additional information about the initiative 
        internalDescription:
          type: string
          description: Additional information about the initiative, for participants only 
        requiresInvitationToJoin:
          type: boolean 
          description: If set, only users who have been invited to join this initiative can join it, otherwise, anyone can join it. Defaults to false.
        isAcceptingNewMembers:
          type: boolean 
          description: If set, new users can join the initiative. Defaults to false.
        isAcceptingNewPortfolios:
          type: boolean 
          description: If set, users that are members of this initiative can add portfolios to it.
        language:
          description: The language this initiative should be conducted in. 
          type: string
          enum: *LANGUAGES
        pactaVersion:
          type: string
          description: The pacta model that this initiative should use, if not specified, the default pacta model will be used. 
        createdAt:
          type: string
          format: date-time
          description: The time at which this initiative was created. 

    InitiativeChanges:
      type: object
      properties:
        name:
          type: string
          description: the human meaningful name of the version of the initiative
        affiliation:
          type: string
          description: the group that sponsors/created/owns this initiative 
        publicDescription:
          type: string
          description: Additional information about the initiative 
        internalDescription:
          type: string
          description: Additional information about the initiative, for participants only 
        requiresInvitationToJoin:
          type: boolean 
          description: If set, only users who have been invited to join this initiative can join it, otherwise, anyone can join it. Defaults to false.
        isAcceptingNewMembers:
          type: boolean 
          description: If set, new users can join the initiative. Defaults to false.
        isAcceptingNewPortfolios:
          type: boolean 
          description: If set, users that are members of this initiative can add portfolios to it.
        language:
          description: The language this initiative should be conducted in. 
          type: string
          enum: *LANGUAGES
        pactaVersion:
          type: string
          description: The pacta model that this initiative should use, if not specified, the default pacta model will be used. 

    User:
      type: object
      required:
        - id
        - enteredEmail
        - requiredEmail
        - admin
        - superAdmin
        - name
        - preferredLanguage
      properties:
        id:
          type: string
          description: Unique id of the user
        enteredEmail:
          type: string
          description: User's email address as entered 
        canonicalEmail:
          type: string
          description: Stanard formatting of the email address of the user
        admin:
          type: boolean 
          description: Whether the user is an administrator of the PACTA platform
        superAdmin:
          type: boolean 
          description: Whether the user is an administrator of the PACTA platform 
        name:
          type: string
          description: Name of the user 
        preferredLanguage:
          description: The user's preferred language, if present 
          type: string
          enum: *LANGUAGES

    UserChanges:
      type:  object
      properties:
        name:
          type: string
          description: The new name of the user 
        preferredLanguage:
          description: The user's new preferred language
          type: string
          enum: *LANGUAGES
        admin:
          type: boolean
          description: Whether the given user is an admin 
        superAdmin:
          type: boolean
          description: Whether the given user is a super admin

    EmptySuccess:
      type: object

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
