# Note: This file has been copied in from https://github.com/RMI/credential-service
openapi: "3.0.0"
info:
  version: 0.0.1
  title: User API
  description: >
    The User API allows users to exchange auth credentials for API credentials
    that can be used with various RMI APIs.
  termsOfService: TODO
  contact:
    name: Silicon Ally
    email: contact@siliconally.org
    url: https://siliconaly.org
  license:
    name: MIT
    url: https://mit-license.org/
servers:
  - url: TODO
paths:
  /login/cookie:
    post:
      summary: Exchange a user JWT token for an auth cookie that can be used with other RMI APIs
      description: |
        Takes an auth system-issued JWT and returns a auth cookie.
      operationId: login
      responses:
        '200':
          description: Cookie response
          headers:
            Set-Cookie:
              schema:
                type: string
                example: __session=abcde12345; Path=/; HttpOnly
        '403':
          description: User is not allowed to log in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /logout/cookie:
    post:
      summary: Log out a user from RMI APIs
      description: |
        Clears an existing API JWT
      operationId: logout
      responses:
        '200':
          description: Cookie response
          headers:
            Set-Cookie:
              schema:
                type: string
                example: __session=abcde12345; Path=/; HttpOnly
  /login/apikey:
    post:
      summary: Exchange a user JWT token for an API key that can be used with other RMI APIs
      description: |
        Takes an auth system-issued JWT and returns a new API key.
      operationId: createAPIKey
      responses:
        '200':
          description: API key response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIKey'
        '403':
          description: User is not allowed to create an API key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    APIKey:
      type: object
      required:
        - id
        - key
      properties:
        id:
          type: string
          description: Unique identifier for the API key
        key:
          type: string
          description: An opaque string used to authenticate with various RMI APIs
        expiresAt:
          type: string
          format: date-time
          description: Timestamp when the token expires, RFC3339-formatted.

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Error message