-- Human Readable Schema

-- This schema is heavily simplified to assist human comprehension it is
-- presented out of order and should not be used for anything other than
-- reference. It is auto-generated by the testpgx package.


CREATE TYPE auth_provider AS ENUM (
    'GOOGLE',
    'FACEBOOK',
    'EMAIL_AND_PASS');


CREATE TABLE schema_migrations_history (
	applied_at timestamp with time zone DEFAULT now() NOT NULL,
	id integer NOT NULL,
	version bigint NOT NULL);
ALTER TABLE ONLY schema_migrations_history ADD CONSTRAINT schema_migrations_history_pkey PRIMARY KEY (id);
ALTER SEQUENCE schema_migrations_history_id_seq OWNED BY schema_migrations_history.id;


CREATE TABLE user_account (
	auth_provider_id text NOT NULL,
	auth_provider_type auth_provider NOT NULL,
	created_at timestamp with time zone DEFAULT now() NOT NULL,
	email text NOT NULL,
	id text NOT NULL,
	name text NOT NULL);
ALTER TABLE ONLY user_account ADD CONSTRAINT user_account_pkey PRIMARY KEY (id);
CREATE INDEX account_auth_provider_id_idx ON user_account USING btree (auth_provider_id);